name: task_manager
description: Task Manager
publish_to: none

environment:
  sdk: ^3.8.0

hooks:
  user_defines:
    win32:
      debug: true
      trace: true

dependencies:
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  win32:
    path: ../../packages/win32

dev_dependencies:
  halildurmus_lints: ^1.0.1

flutter:
  uses-material-design: true
