name: service_manager_cli
description: Service Manager CLI
publish_to: none

environment:
  sdk: ^3.8.0

hooks:
  user_defines:
    win32:
      debug: true
      trace: true

dependencies:
  ffi: ^2.1.4
  win32:
    path: ../../packages/win32

dev_dependencies:
  halildurmus_lints: ^1.0.1

executables:
  service_manager_cli:
