name: generator
description: Generates various Win32 API projections using Windows metadata.
publish_to: none

environment:
  sdk: ^3.9.0-0

resolution: workspace

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  # For extracting the contents of the .nupkg files.
  archive: ^4.0.7

  # Handle command-line arguments for scripts.
  args: ^2.6.0

  # For generating Dart code.
  code_builder: ^4.10.1

  # For formatting Dart code (APIs for performing dart format).
  dart_style: ^3.1.0

  # Foreign Function Interface extension methods.
  ffi: ^2.1.4

  # For logging messages to the console.
  logging: ^1.3.0

  meta: ^1.16.0

  # For de-serializing Messagepack formatted data.
  msgpack_dart: ^1.0.1

  # To download NuGet packages.
  nuget: ^0.2.0

  # For manipulating paths.
  path: ^1.9.1

  # Windows metadata for automatically generating API signatures.
  winmd: ^7.0.0

  # For parsing YAML files.
  yaml: ^3.1.3

dev_dependencies:
  # Used for expressing test expectations.
  checks: ^0.3.0

  # Help ensure that the code is well-written.
  halildurmus_lints: ^1.0.1

  # Used for running Git hooks.
  # halildurmus_hooks:
  #   git:
  #     url: https://github.com/halildurmus/workflows.git
  #     path: packages/hooks

  # Running the test suite.
  test: ^1.26.2

executables:
  generator:
