name: win32_explorer
description: Drive explorer
publish_to: none

environment:
  sdk: ^3.8.0

hooks:
  user_defines:
    win32:
      debug: true
      trace: true

dependencies:
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  menubar:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/menubar
  path_provider: ^2.1.5
  win32:
    path: ../../packages/win32

dev_dependencies:
  halildurmus_lints: ^1.0.1

flutter:
  uses-material-design: true
